def get_responses():
    responses = {
    ("hi", "hello", "howdy"): "Hello! How can I help you?",
    ("goodbye","bye","bye bye"): "Please say bye robo if you want to stop this conversation",
    "headache": "You might want to take some rest and drink plenty of water. If it persists, consider taking a pain reliever like acetaminophen.",
    ("stomach ache","stomach"): "Try to eat light and avoid spicy or greasy foods. Consider taking an antacid or over-the-counter medication for relief.",
    ("sore throat","throat","cold"): "Gargle with warm salt water and drink soothing liquids like tea with honey. Consider taking lozenges or throat sprays for relief.",
    "common cold": "Rest, drink plenty of fluids, and consider over-the-counter medications like decongestants or pain relievers if needed. If symptoms worsen, consult a healthcare professional.",
    ("injury","swelling","swollen","hurt"): "If it's a minor injury, apply ice to reduce swelling and elevate the affected area. For more serious injuries, seek medical attention immediately.",
    ("healthy diet","diet","food"): "A healthy diet includes a variety of fruits, vegetables, whole grains, lean proteins, and healthy fats. Remember to stay hydrated by drinking plenty of water.",
    "exercise": "Regular exercise is important for overall health. Aim for at least 30 minutes of moderate-intensity exercise most days of the week.",
    "mental health": "Taking care of your mental health is just as important as your physical health. Practice self-care, seek support when needed, and consider talking to a therapist or counselor.",
    ( "weight loss","weight"): "To lose weight, focus on a balanced diet with fewer calories and regular exercise. Consider consulting a nutritionist or personal trainer for personalized advice.",
    "nutrition": "Nutrition is key to overall health. Aim for a balanced diet rich in fruits, vegetables, whole grains, lean proteins, and healthy fats.",
    "stress": "Managing stress is important for both physical and mental health. Try relaxation techniques such as deep breathing, meditation, or yoga.",
    "sleep": "Quality sleep is essential for good health. Aim for 7-9 hours of sleep per night and establish a regular sleep schedule.",
    ("hydration","water"): "Stay hydrated by drinking plenty of water throughout the day. Aim for at least 8 glasses of water daily, more if you're physically active.",
    "heart": "Maintain heart health by eating a heart-healthy diet, exercising regularly, avoiding smoking, and managing stress. Regular check-ups with your doctor are also important.",
    ("diabetes","sugar"): "If you have diabetes, monitor your blood sugar levels regularly, follow a balanced diet, exercise regularly, and take medications as prescribed by your healthcare provider.",
    "cholesterol ": "To manage cholesterol levels, focus on a diet low in saturated and trans fats, increase consumption of fruits, vegetables, and whole grains, and engage in regular physical activity.",
    "blood pressure": "Monitor your blood pressure regularly, maintain a healthy weight, limit sodium intake, exercise regularly, and manage stress to help control blood pressure levels.",
    "skin care": "Practice good skincare habits by cleansing your skin regularly, using sunscreen, moisturizing, and avoiding excessive sun exposure and harsh chemicals.",
    "eye ": "Protect your eyes by wearing sunglasses outdoors, taking regular breaks when working on screens, maintaining a healthy diet rich in antioxidants, and scheduling regular eye exams.",
    ("oral hygiene","teeth","tooth"): "Maintain good oral hygiene by brushing twice a day, flossing daily, using mouthwash, and visiting your dentist for regular check-ups and cleanings.",
    ("smoking","cigerette"): "Quitting smoking is one of the best things you can do for your health. Consider seeking support from a healthcare professional or support group.",
    "alcohol ": "If you choose to drink alcohol, do so in moderation. Limit intake to no more than one drink per day for women and two drinks per day for men.",
    ("immune ","immunity"): "Boost your immune system by maintaining a balanced diet, getting regular exercise, managing stress, getting enough sleep, and avoiding smoking and excessive alcohol consumption.",
    ("vitamin", "supplements"): "Consider taking vitamin supplements only if recommended by a healthcare professional and if you have deficiencies that cannot be addressed through diet alone.",
    "bone ": "Maintain bone health by consuming adequate calcium and vitamin D, engaging in weight-bearing exercises, avoiding smoking, and limiting alcohol intake.",
    "joint ": "To support joint health, maintain a healthy weight, engage in regular exercise, eat a balanced diet rich in omega-3 fatty acids and antioxidants, and consider supplements like glucosamine and chondroitin.",
    ("digestive","digestion"): "Promote digestive health by consuming fiber-rich foods, staying hydrated, managing stress, exercising regularly, and avoiding excessive intake of alcohol and caffeine.",
    "vision": "To maintain vision health, get regular eye exams, eat a diet rich in antioxidants and omega-3 fatty acids, protect your eyes from UV radiation, and take breaks when working on screens.",
    ("respiratory","breath","breathing"): "To support respiratory health, avoid smoking and exposure to secondhand smoke, exercise regularly, maintain a healthy weight, and practice good hygiene to prevent respiratory infections.",
    "blood sugar management": "Monitor your blood sugar levels regularly, follow a balanced diet with controlled carbohydrate intake, engage in regular physical activity, and take medications as prescribed by your healthcare provider.",
    "mental wellbeing": "Prioritize mental wellbeing by practicing self-care, seeking support when needed, staying connected with others, engaging in activities you enjoy, and considering therapy or counseling if you're struggling.",
    "stress reduction ": "Manage stress with techniques like deep breathing, meditation, yoga, progressive muscle relaxation, spending time in nature, and engaging in hobbies or activities that bring you joy.",
    "eating habits": "Cultivate healthy eating habits by practicing mindful eating, listening to your body's hunger and fullness cues, cooking at home more often, and enjoying a variety of foods in moderation.",
    "stress-relieving activities": "Engage in stress-relieving activities like walking, spending time in nature, practicing mindfulness, journaling, listening to music, or engaging in creative pursuits.",
    "relaxation ": "Incorporate relaxation techniques into your routine, such as deep breathing exercises, progressive muscle relaxation, guided imagery, or aromatherapy, to promote relaxation and reduce stress.",
    "nutrition ": "For older adults, it's important to focus on nutrient-dense foods like fruits, vegetables, whole grains, and lean proteins to support overall health.",
    "exercise tips": "When exercising as an older adult, focus on activities that improve strength, flexibility, and balance. Consult with a healthcare provider before starting a new exercise routine.",
    "memory tips": "To maintain memory and cognitive function, older adults can engage in activities like puzzles, reading, and socializing. Stay mentally active to keep the mind sharp.",

}
    return responses